service: chat

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-1
functions:
  getMessages:
    handler: src/handlers/messages.get
    events:
      - http:
          path: messages
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-include-dependencies
# package:
#   exclude:
#     - node_modules/**/*
#   include:
#     src/handlers/*.ts
    