service: chat-app

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-1
functions:
  getMessages:
    handler: src/handlers/messages.get
    events:
      - http:
          path: messages
          method: get
  writeMessage:
    handler: src/handlers/writeMessage.writeMessage
    events:
      - http:
          path: messages
          method: post

  drop:
    handler: src/handlers/drop.dropTables
    events:
      - http:
          path: drop
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline
# package:
#   exclude:
#     - node_modules/**/*
#   include:
#     src/handlers/*.ts
